### ISSUE TITLE
Allowing incremental_columns when using query option

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-input-jdbc#100] opened 2017-03-22 10:58 UTC
Currently 'incremental_columns' and 'last_record' parameters are not supported if 'query' parameter is set.

Is there specific reason for this?
Tested few queries(with lines 308-309 removed from AbstractJdbcInputPlugin.java) and things worked as expected.

**Comment by hito4t** [comment] 2017-03-23 01:39
Hi
First, the plugin built query for incremental loading from table name and didn't support `query` parameter.
After that, the plugin came to be able to build query for incremental loading from any query, but the check was not deleted.

I think we can delete the check.
https://github.com/embulk/embulk-input-jdbc/blob/master/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/AbstractJdbcInputPlugin.java#L326-L327

@frsyuki
What do you think about it?

**Comment by frsyuki** [comment] 2017-03-27 04:36
With `incremental_columns` option, the plugin needs to generate add a WHERE condition and ORDER BY clause. When `query` option is given, `JdbcInputConnection#wrapIncrementalQuery` method runs and it adds WHERE and ORDER BY by wrapping the original `query` in a subquery. So, `query` option with `incremental_columns` is an expected use case. I think it's ok to remove the outdated validation, as @hito4t mentions.

A concern is that wrapping a query in a subquery spoils utilization of table indexes in MySQL (in some cases) although the generated query seems totally reasonable to use an index on ORDER BY column(s). This concerns me because users won't expect that using `query` option and not using `query` option won't make significant differences (but actually they do). And they'll realize this problem only when Embulk made the database overloaded, in current implementation.

It would be great if there is an idea to mitigate this unexpected behavior, such as adding a document or warning message. For PostgreSQL, Redshift, or other databases that have reasonable query optimizer, I don't have concerns.

**Comment by y-ken** [comment] 2018-03-20 01:28
Hi @frsyuki @hito4t 
I need this enhancement so much.
To avoid unexpected behavior, I suggest to introduce a option or placeholder.
How about that?

* If it does not have placeholder, just keep current subquery behavior
* If it has a option to disable subquery
  * If the query already has `ORDER BY`, warn it end exit.
  * If the query contain `WHERE`, wrap current condition with `()`and add `AND id > ?`
  * Add `ORDER BY` statement.

For example
```
-- input
SELECT
  foo.id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
WHERE
  hoge IS NOT NULL

-- output
SELECT
  foo.id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
WHERE
  (
    hoge IS NOT NULL
  )
  AND id > ?
ORDER BY
  id
```

Another idea, introduce placeholder like following (keywords need to be refine)
  * {WHERE_CONDITION} 
  * {ORDER_BY_CLAUSE}

```
-- input
SELECT
  foo.id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
WHERE
  (
    hoge IS NOT NULL
  )
  AND {WHERE_CONDITION} 
ORDER BY
  {ORDER_BY_CLAUSE}

-- output
SELECT
  foo.id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
WHERE
  (
    hoge IS NOT NULL
  )
  AND id > ?
ORDER BY
  id
```

**Comment by hito4t** [comment] 2018-03-23 04:20
@y-ken 
Thank you for your comment!

Introducing placeholder is a nice idea!
I think it is not easy to detect correct `WHERE` clause or `ORDER BY` clause because complex queries may have multiple `WHERE`s.

To implement the new feature, we should consider the following problems.

- users should specify placeholder characters (DBMSs have various special characters. And string literals or comments might contain placeholder characters.)
- query might already have WHERE term or not (should embulk-input-jdbc add `AND`? And embulk-input-jdbc won't add `WHERE` for the first time.)
- query might already have ORDER BY column or not (should embulk-input-jdbc add `,`?)

Please give feedback if you have any ideas.

**Comment by sakama** [comment] 2018-03-23 06:07
@hito4t JFYI: Actually, @y-ken 's request is from our company.
We can send PR after requirements is fixed on this issue. Thanks.

**Comment by y-ken** [comment] 2018-04-05 08:13
Hi @hito4t 

Discussed TD internally with @muga @dmikurube @sakama .
We propose following enhances. Do you agree to submit the plan and PR of this?

# Abstract

To use incremental_columns, we cannot use `query` option. I want to use incremental with join tables.
That query does not heavy because mysql optimizer works well.

1. unlock feature
For light use. Enable to work using `query` and `incremental_coloumns` option.
It generated conditions as subquery.  It cause slow query in some situation.
Of course, It is need to notice for document.

2. introduce placeholder like PDO
It can express full customized sql.

# Detail

## 1. unlock feature

* automated query rewrite are simple. just quote `(` and `)` after `WHERE`
* outputs generated sql in log

### sample configuration

```
in:
  type: mysql
  host: 127.0.0.1
  user: {{ env.mysql_user }}
  password: {{ env.mysql_password }}
  query: |    
    SELECT
      foo.id as foo_id, bar.name
    FROM
      foo LEFT JOIN bar ON foo.id = bar.id
    WHERE
      foo.hoge IS NOT NULL
  incremental_columns:
  - foo_id
  incremental: true

out:
  type: stdout
```

### sample sql

generated sql if last_record are`{"last_record":{"id":5}}`.
It adds last_record condition after quote the exist where condition.
And also adds ORDER  BY clause as like previous implements.

```sql
SELECT
  foo.id as foo_id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
WHERE
  (
    foo.hoge IS NOT NULL
  )
  AND foo.id > 5
ORDER BY
  foo.id ASC
```

## 2. introduce placeholder like PDO

* replace `?` with `incremental_columns` array.
* raise error if does not have same number of`?` or `ORDER BY`.
* outputs generated sql in log

### sample configuration

It acts like PDO. `?` replace incremental_columns with keeping order.
This mode need static `ORDER BY` clause in `query` option.

```sql
in:
  type: mysql
  host: 127.0.0.1
  user: {{ env.mysql_user }}
  password: {{ env.mysql_password }}
  query: |    
    SELECT
      foo.id as foo_id, bar.name
    FROM
      foo LEFT JOIN bar ON foo.id = bar.id
    WHERE
      foo.hoge IS NOT NULL
      AND foo.id > ?
    ORDER BY
      foo.id ASC
  incremental_columns:
  - foo_id
  incremental: true

out:
  type: stdout
```

### sample sql

generated sql if last_record are`{"last_record":{"id":5}}`.

And also adds ORDER  BY clause as like previous implements.

```sql
SELECT
  foo.id as foo_id, bar.name
FROM
  foo LEFT JOIN bar ON foo.id = bar.id
    WHERE
      foo.hoge IS NOT NULL
      AND foo.id > 5
ORDER BY
  foo.id ASC
```

**note**
* Query column name aliasing tested with MySQL and PostgreSQL.

**Comment by hito4t** [comment] 2018-04-13 05:05
@y-ken 
Thank you for the proposition!

> raise error if does not have same number of? or ORDER BY.

We need more ?s than the count of incremental columns when it is more than 1.
(See https://github.com/embulk/embulk-input-jdbc/pull/55#issuecomment-236758754)

I think that placeholders need to have names.

**Comment by y-ken** [comment] 2018-05-07 17:16
@hito4t 
For now, I understand what you are aware to.
How do you think this idea?

I'm suggesting to use named placeholder for sql. like `:foobar`.
https://www.javaworld.com/article/2077706/core-java/named-parameters-for-preparedstatement.html

* incremental_columns using column name which aliased in select statement if it changed
* In the case of incremental multi column handling like https://github.com/embulk/embulk-input-jdbc/pull/55#issuecomment-236758754, It can write with placeholder like this. 
`(id = :id AND sub_id > :sub_id) OR id > :id` 
  * it comes `(id = 2 AND sub_id > 3) OR id > 2` as 

```sql
in:
  type: mysql
  host: 127.0.0.1
  user: {{ env.mysql_user }}
  password: {{ env.mysql_password }}
  query: |    
    SELECT
      foo.id as foo_id, bar.name
    FROM
      foo LEFT JOIN bar ON foo.id = bar.id
    WHERE
      foo.hoge IS NOT NULL
      AND foo.id > :foo_id
    ORDER BY
      foo.id ASC
  incremental_columns:
  - foo_id
  incremental: true

out:
  type: stdout
```

And, It should be better to have raise error if it comes duplicated incremental columns value.
For error handling which just idea, in the case of last incremental values was [1,3] then next are same as [1,3] coming, it might be better to raise error.

**Comment by hito4t** [comment] 2018-05-11 04:29
@y-ken 
Thank you for your response.
It's a good idea to use named placeholder!
I'm looking forward to PR!

**Closed** 2018-11-14 02:19 UTC
